name: release-build

on:
    workflow_run:
        workflows: [ "Test and coverage report" ]
        branches: [ "main" ]
        types:
          - completed

permissions:
    # Permisos necesarios para escribir contenido, paquetes, y leer issues y pull requests
    contents: write
    packages: write
    issues: read
    pull-requests: read

jobs:
  semantic-release:
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"
    name: Semantic Release
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      version: ${{ steps.export_version.outputs.version }}  

    steps:
      # Clonar repositorio
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js deps
        run: npm install
          
      # Crear un archivo vacío para almacenar la versión generada por semantic-release    
      - name: Create empty semantic
        run: touch semantic_release_version.txt
  
      # Ejecutar semantic-release para generar versiones  
      - name: generar version
        id: semantic_release
        run: |
          npx semantic-release --debug | tee semantic_release_output.txt
          # Si Semantic Release no genera una nueva versión, capturamos la última versión existente
          if grep -q "There are no relevant changes, so no new version is released" semantic_release_output.txt; then
            echo "No new version generated. Fetching the latest version tag."
            VERSION=$(git describe --tags --abbrev=0)
          else
            # Limpiar y extraer solo la versión
            VERSION=$(grep -Po "\[semantic-release\].*Published release \K([0-9]+\.[0-9]+\.[0-9]+)" semantic_release_output.txt || echo "")
          fi
          echo "Version extracted: $VERSION"
          echo "$VERSION" > semantic_release_version.txt  

      # Verificar el contenido del archivo de versión generado    
      - name: Debug semantic_release_version.txt
        run: |
          ls -l semantic_release_version.txt
          cat semantic_release_version.txt || echo "File is empty or does not exist"

      # Pasar la variable version o otros jobs 
      - name: set output VERSION
        id: export_version
        run: |
          VERSION=$(cat semantic_release_version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update FastAPI version
        run: |
          VERSION=$(cat semantic_release_version.txt)
          echo 'VERSION = "'$VERSION'"' > app/version.py
          git config user.name "semantic-release-bot"
          git config user.email "semantic-release@github.com"
          git add app/version.py
          git commit -m "chore: update FastAPI version to $VERSION [skip ci]" || echo "No changes to commit"
          git push origin main

  docker_image:
    needs: semantic-release
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.semantic-release.outputs.version }}
    
    steps:
      - name: Print received version
        run: echo "VERSION=${VERSION}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Configurar QEMU para construir imágenes Docker multiplataforma      
      - name: Set up QEMU
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-qemu-action@v3   
        
      # Configurar Docker Buildx para construir imágenes multiplataforma  
      - name: Set up Docker Buildx
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-buildx-action@v3

      # Iniciar sesión en el contenedor del registro GHCR 
      - name: Docker Login in GHCR
        if: ${{ env.VERSION != '' }}
        uses: docker/login-action@v3
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Iniciar sesión en Docker Hub    
      - name: Login to Docker Hub
        if: ${{ env.VERSION != '' }}
        uses: docker/login-action@v3
        id: configure-login-dockerhub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Obtener el nombre base del repositorio 
      - name: repo-basename   
        id: repo-basename
        run: |
          echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
        shell: bash
      
      # Generar metadatos de Docker y ghcr para etiquetas y nombres de imagen  
      - name: Generar metadatos docker y ghcr
        if: ${{ env.VERSION != '' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/remote
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.VERSION }}
            latest

      # Depurar los metadatos generados      
      - name: Debug Docker metadata
        run: |
            echo "Tags: ${{ steps.meta.outputs.tags }}"
            echo "Labels: ${{ steps.meta.outputs.labels }}"            

      # Construir y subir la imagen Docker      
      - name: Build and push Docker image
        if: ${{ env.VERSION != '' }}
        uses: docker/build-push-action@v6
        with:
          context: . # Contexto de construcción
          file: ./Dockerfile # Ruta al Dockerfile
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}